name: Certora Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
      - v*
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  certora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: yarn install
      - name: Run patches
        run: |
          git apply certora/patch/prover_optimization.patch
          git apply certora/patch/senderCreatorMunge.patch
      - name: Account abstraction Rules
        uses: Certora/certora-run-action@v1
        with:
          configurations: |-
            certora/conf/management.conf
            certora/conf/management_no_havoc.conf
            certora/conf/nonce.conf
            certora/conf/nonceOneTime.conf
            certora/conf/nonHandleOps.conf
            certora/conf/EntryPoint.conf --rule onlyValidatedCalls_3HandleAggregatedOps333 --loop_iter 8
            certora/conf/EntryPoint.conf --rule onlyValidatedCalls_3HandleAggregatedOps233 onlyValidatedCalls_3HandleAggregatedOps323 onlyValidatedCalls_3HandleAggregatedOps332 --loop_iter 7
            certora/conf/EntryPoint.conf --rule onlyValidatedCalls_3HandleAggregatedOps133 onlyValidatedCalls_3HandleAggregatedOps223 onlyValidatedCalls_3HandleAggregatedOps232 onlyValidatedCalls_3HandleAggregatedOps313 onlyValidatedCalls_3HandleAggregatedOps322 onlyValidatedCalls_3HandleAggregatedOps331 --loop_iter 6
            certora/conf/EntryPoint.conf --rule onlyValidatedCalls_3HandleAggregatedOps033 onlyValidatedCalls_3HandleAggregatedOps123 onlyValidatedCalls_3HandleAggregatedOps132 onlyValidatedCalls_3HandleAggregatedOps213 onlyValidatedCalls_3HandleAggregatedOps222 onlyValidatedCalls_3HandleAggregatedOps231 onlyValidatedCalls_3HandleAggregatedOps303 onlyValidatedCalls_3HandleAggregatedOps312 onlyValidatedCalls_3HandleAggregatedOps321 onlyValidatedCalls_3HandleAggregatedOps330 --loop_iter 5
            certora/conf/EntryPoint.conf --exclude_rule onlyValidatedCalls_3HandleAggregatedOps333 onlyValidatedCalls_3HandleAggregatedOps233 onlyValidatedCalls_3HandleAggregatedOps323 onlyValidatedCalls_3HandleAggregatedOps332 onlyValidatedCalls_3HandleAggregatedOps133 onlyValidatedCalls_3HandleAggregatedOps223 onlyValidatedCalls_3HandleAggregatedOps232 onlyValidatedCalls_3HandleAggregatedOps313 onlyValidatedCalls_3HandleAggregatedOps322 onlyValidatedCalls_3HandleAggregatedOps331 onlyValidatedCalls_3HandleAggregatedOps033 onlyValidatedCalls_3HandleAggregatedOps123 onlyValidatedCalls_3HandleAggregatedOps132 onlyValidatedCalls_3HandleAggregatedOps213 onlyValidatedCalls_3HandleAggregatedOps222 onlyValidatedCalls_3HandleAggregatedOps231 onlyValidatedCalls_3HandleAggregatedOps303 onlyValidatedCalls_3HandleAggregatedOps312 onlyValidatedCalls_3HandleAggregatedOps321 onlyValidatedCalls_3HandleAggregatedOps330
            certora/conf/EntryPoint_sanity.conf --rule "sanity_onlyValidatedCalls_3HandleAggregatedOps2*" --exclude_rule sanity_onlyValidatedCalls_3HandleAggregatedOps233 sanity_onlyValidatedCalls_3HandleAggregatedOps223 sanity_onlyValidatedCalls_3HandleAggregatedOps232 sanity_onlyValidatedCalls_3HandleAggregatedOps213 sanity_onlyValidatedCalls_3HandleAggregatedOps222 sanity_onlyValidatedCalls_3HandleAggregatedOps231
          solc-versions: 0.8.28
          job-name: "Account abstraction rules Rules"
          cli-version: 7.28.0
          certora-key: ${{ secrets.CERTORAKEY }}